### PR TITLE
Adds more test cases

### PR DESCRIPTION
**Pull request by fox1t**
Still missing ESM package!

`npm run all` or `yarn all`

There are many strainge behaviours on all module systems. Yet, the most consistent one is still the `infamous triplet`.

We need to add also ESM package in `node_modules`.

### CODE REVIEW

**Comment by fox1t** [comment]
@voxpelli here we are, after 2 days of work :)
P.S. I can't add you as a reviewer!

**Comment by fox1t** [comment]
@voxpelli I need to merge this PR in order to go on. If you want to discuss something, feel free to open an issue/new PR.

**Comment by voxpelli** [comment]
@fox1t Cool, if you want some input on anything specific, then feel free to do the same, I'm following along from the side.

(If you add me as a collaborator, then you can assign me as a reviewer I think)

**Comment by fox1t** [comment]
@voxpelli added as a collaborator!

There are some notable quirks:
- https://github.com/fox1t/modules-playground/blob/master/modules/typed-cjs/ts.js#L49 -> TS `import()` is entirely different from Node.js `import()` and neither typed-cjs nor TS knows the real final shape of the imported module. I suppose this is a TS bug because TS considers `import()`  as a `require()` wrapped in a Promise. It is not a case, though.
- https://github.com/fox1t/modules-playground/blob/master/modules/esm/ts-namespace.mjs#L36 -> the fix introduced in node to analyze for named exports in CJS is not working since TS doesn't use `module.exports` but https://github.com/fox1t/modules-playground/blob/master/modules/node_modules/ts-namespace/build/index.js#L3
- the `infamous triplet` style is confirmed as the more consistent across all of the import/require.
- to reproduce the triplet in TS, we need to create an index.js entry point for the package manually: https://github.com/fox1t/modules-playground/blob/master/modules/node_modules/ts-triplet/index.js

**Comment by voxpelli** [comment]
@fox1t Can you add them as issues and we can discuss them individually + maybe split the work on them between us?

Thanks for adding me! Accepted :)

**Pull request merged**
